name: Utils
version: 0.26
date: 12/02/2016
description: Utility functions in GAP

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Stefan Kohl
      url: http://www.gap-system.org/DevelopersPages/StefanKohl/
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://pages.bangor.ac.uk/~mas023/chda/utils/
readme: http://pages.bangor.ac.uk/~mas023/chda/utils/README.md
packageinfo: http://pages.bangor.ac.uk/~mas023/chda/utils/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://pages.bangor.ac.uk/~mas023/chda/utils/utils-0.26.tar.gz

abstract: The <span class="pkgname">Utils</span> package provides a collection   of utility functions gleaned from many packages.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
