name: utils
version: 0.71
date: 2021-11-15
description: |
    Utility functions in GAP

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: Stefan Kohl
      url: https://www.gap-system.org/DevelopersPages/StefanKohl/
    - name: Frank Lübeck
      url: http://www.math.rwth-aachen.de/~Frank.Luebeck
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "GAPDoc"
      version: ">= 1.6.4"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">= 2.16"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/utils
readme: README.md
packageinfo: https://gap-packages.github.io/utils/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/utils/releases/download/v0.71/utils-0.71.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/utils/releases/download/v0.71/utils-0.71.zip

abstract: |
    The <span class="pkgname">Utils</span> package provides a collection   of utility functions gleaned from many packages.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
