name: utils
version: 0.58
date: 2018-09-12
description: |
    Utility functions in GAP

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: Stefan Kohl
      url: https://www.gap-system.org/DevelopersPages/StefanKohl/
    - name: Frank Lübeck
      url: http://www.math.rwth-aachen.de/~Frank.Luebeck
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

maintainers:
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

GAP: ">=4.9.2"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Polycyclic"
      version: ">= 2.14"
      url: "https://gap-packages.github.io/polycyclic/"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">= 2018.02.14"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://gap-packages.github.io/utils
readme: README.md
packageinfo: https://gap-packages.github.io/utils/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/utils/releases/download/v0.58/utils-0.58.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/utils/releases/download/v0.58/utils-0.58.zip

abstract: |
    The <span class="pkgname">Utils</span> package provides a collection   of utility functions gleaned from many packages.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
